name: Tests

on:
  push:
    branches:
      - '**'

jobs:
  fmt:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt

      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Run cargo check on stable toolchain
        uses: actions-rs/cargo@v1
        with:
          command: check
          toolchain: stable

      - name: Install nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly

      - name: Run cargo check on nightly toolchain
        uses: actions-rs/cargo@v1
        with:
          command: check
          toolchain: nightly

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Test on stable toolchain
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features --no-fail-fast
          toolchain: stable

      - name: Install nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly

      - name: Test on nightly toolchain
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features --no-fail-fast
          toolchain: nightly
